# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Wed Sep 09 14:54:24 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1fF
set_units -time 1000ps

# Set the current design
current_design register_read

create_clock -name "clk" -period 3.333 -waveform {0.0 1.6665} [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_false_path -from [get_ports rst_n]
set_clock_gating_check -setup 0.0 
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[rob_tag][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[rob_tag][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[rob_tag][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[rob_tag][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[rob_tag][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src2_data][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[src1_data][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[except]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[cause][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[cause][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[exec_unit_uop][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[exec_unit_uop][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[exec_unit_uop][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[exec_unit_uop][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[exec_unit_uop][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[exec_unit_uop][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[func_unit_type][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[func_unit_type][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[instr_class][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[instr_class][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[instr_class][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[imm_val][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[predicted_pc][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[pc][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[reg_we]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2_valid]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1_valid]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[old_p_dest][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[old_p_dest][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[old_p_dest][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[old_p_dest][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[old_p_dest][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[old_p_dest][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_dest][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_dest][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_dest][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_dest][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_dest][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_dest][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src2][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1][5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1][4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1][3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1][2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1][1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[p_src1][0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.8332 [get_ports {execute_out[valid]}]
set_max_fanout 16.000 [current_design]
set_max_transition 0.2 [current_design]
set_ideal_network [get_ports rst_n]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.1 [get_clocks clk]
set_clock_uncertainty -hold 0.05 [get_clocks clk]
