# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Tue Sep 29 10:48:11 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1fF
set_units -time 1000ps

# Set the current design
current_design orion_core

create_clock -name "core_clk" -period 4.25 -waveform {0.0 2.125} [get_ports clk]
set_clock_transition 0.1 [get_clocks core_clk]
set_load -pin_load 5.0 [get_ports {imem_addr[7]}]
set_load -pin_load 5.0 [get_ports {imem_addr[6]}]
set_load -pin_load 5.0 [get_ports {imem_addr[5]}]
set_load -pin_load 5.0 [get_ports {imem_addr[4]}]
set_load -pin_load 5.0 [get_ports {imem_addr[3]}]
set_load -pin_load 5.0 [get_ports {imem_addr[2]}]
set_load -pin_load 5.0 [get_ports {imem_addr[1]}]
set_load -pin_load 5.0 [get_ports {imem_addr[0]}]
set_false_path -from [get_ports rst_n]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[31]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[30]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[29]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[28]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[27]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[26]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[25]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[24]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[23]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[22]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[21]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[20]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[19]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[18]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[17]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[16]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[15]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[14]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[13]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[12]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[11]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[10]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[9]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[8]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[7]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[6]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[5]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[4]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[3]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[2]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[1]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_rdata[0]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[31]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[30]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[29]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[28]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[27]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[26]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[25]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[24]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[23]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[22]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[21]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[20]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[19]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[18]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[17]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[16]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[15]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[14]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[13]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[12]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[11]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[10]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[9]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[8]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[7]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[6]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[5]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[4]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[3]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[2]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[1]}]
set_input_delay -clock [get_clocks core_clk] -add_delay -min 0.425 [get_ports {imem_rdata[0]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[7]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[6]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[5]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[4]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[3]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[2]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[1]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -max 1.275 [get_ports {imem_addr[0]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[7]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[6]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[5]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[4]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[3]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[2]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[1]}]
set_output_delay -clock [get_clocks core_clk] -add_delay -min 0.2125 [get_ports {imem_addr[0]}]
set_max_fanout 16.000 [current_design]
set_max_transition 0.5 [current_design]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[31]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[30]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[29]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[28]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[27]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[26]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[25]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[24]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[23]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[22]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[21]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[20]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[19]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[18]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[17]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[16]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[15]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[14]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[13]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[12]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[11]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[10]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[9]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[8]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[7]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[6]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[5]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[4]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[3]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[2]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[1]}]
set_driving_cell -lib_cell BUF_X4 -library NangateOpenCellLibrary -pin "Z" [get_ports {imem_rdata[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.15 [get_clocks core_clk]
set_clock_uncertainty -hold 0.15 [get_clocks core_clk]
